### PR TITLE
Add Invite page

### PR DESCRIPTION
**Pull request by TheTrio**
1. Refactored (a lot) of code
2.  Added new invite page
3. Modified `/rooms/get` to return another property `userInRoom`
4. Cleaned up unused files and functions

Still not sure about the design for the invite page. Currently, looks something like this

image

The text is mostly just a placeholder. We should probably decide on something to put in there.

### CODE REVIEW

**Comment by TheTrio** [comment]
Also, afaik, we currently don't have the access to `roomName` on the front end. Maybe `/rooms/get` should return the `roomName` as well?

**Comment by rushitote** [comment]
> Also, afaik, we currently don't have the access to `roomName` on the front end. Maybe `/rooms/get` should return the `roomName` as well?

Yep it would be even better if we return all the information of the room (currently the name and owner) with it.

**Comment by TheTrio** [comment]
Updated the layout a bit

image

Am marking this for review.

**Comment by TheTrio** [comment]
> Yep it would be even better if we return all the information of the room (currently the name and owner) with it.

Probably best to do that in another PR. Have opened an issue #26

**Review by rushitote — APPROVED** [review]
Looks good!

**Pull request merged**
